<?php

use Illuminate\Database\Seeder;
use App\City;
class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        City::create(['name' => 'Abriaquí', 'department_id' =>5]);
        City::create(['name' => 'Acacías', 'department_id' =>50]);
        City::create(['name' => 'Acandí', 'department_id' =>27]);
        City::create(['name' => 'Acevedo', 'department_id' =>41]);
        City::create(['name' => 'Achí', 'department_id' =>13]);
        City::create(['name' => 'Agrado', 'department_id' =>41]);
        City::create(['name' => 'Agua de Dios', 'department_id' =>25]);
        City::create(['name' => 'Aguachica', 'department_id' =>20]);
        City::create(['name' => 'Aguada', 'department_id' =>68]);
        City::create(['name' => 'Aguadas', 'department_id' =>17]);
        City::create(['name' => 'Aguazul', 'department_id' =>85]);
        City::create(['name' => 'Agustín Codazzi', 'department_id' =>20]);
        City::create(['name' => 'Aipe', 'department_id' =>41]);
        City::create(['name' => 'Albania', 'department_id' =>18]);
        City::create(['name' => 'Albania', 'department_id' =>44]);
        City::create(['name' => 'Albania', 'department_id' =>68]);
        City::create(['name' => 'Albán', 'department_id' =>25]);
        City::create(['name' => 'Albán [San José]', 'department_id' =>52]);
        City::create(['name' => 'Alcalá', 'department_id' =>76]);
        City::create(['name' => 'Alejandría', 'department_id' =>5]);
        City::create(['name' => 'Algarrobo', 'department_id' =>47]);
        City::create(['name' => 'Algeciras', 'department_id' =>41]);
        City::create(['name' => 'Almaguer', 'department_id' =>19]);
        City::create(['name' => 'Almeida', 'department_id' =>15]);
        City::create(['name' => 'Alpujarra', 'department_id' =>73]);
        City::create(['name' => 'Altamira', 'department_id' =>41]);
        City::create(['name' => 'Alto Baudó [Pie de Pato]', 'department_id' =>27]);
        City::create(['name' => 'Altos del Rosario', 'department_id' =>13]);
        City::create(['name' => 'Alvarado', 'department_id' =>73]);
        City::create(['name' => 'Amagá', 'department_id' =>5]);
        City::create(['name' => 'Amalfi', 'department_id' =>5]);
        City::create(['name' => 'Ambalema', 'department_id' =>73]);
        City::create(['name' => 'Anapoima', 'department_id' =>25]);
        City::create(['name' => 'Ancuyá', 'department_id' =>52]);
        City::create(['name' => 'Andalucía', 'department_id' =>76]);
        City::create(['name' => 'Andes', 'department_id' =>5]);
        City::create(['name' => 'Angelópolis', 'department_id' =>5]);
        City::create(['name' => 'Angostura', 'department_id' =>5]);
        City::create(['name' => 'Anolaima', 'department_id' =>25]);
        City::create(['name' => 'Anorí', 'department_id' =>5]);
        City::create(['name' => 'Anserma', 'department_id' =>17]);
        City::create(['name' => 'Ansermanuevo', 'department_id' =>76]);
        City::create(['name' => 'Anzoátegui', 'department_id' =>73]);
        City::create(['name' => 'Anzá', 'department_id' =>5]);
        City::create(['name' => 'Apartadó', 'department_id' =>5]);
        City::create(['name' => 'Apulo', 'department_id' =>25]);
        City::create(['name' => 'Apía', 'department_id' =>66]);
        City::create(['name' => 'Aquitania', 'department_id' =>15]);
        City::create(['name' => 'Aracataca', 'department_id' =>47]);
        City::create(['name' => 'Aranzazu', 'department_id' =>17]);
        City::create(['name' => 'Aratoca', 'department_id' =>68]);
        City::create(['name' => 'Arauca', 'department_id' =>81]);
        City::create(['name' => 'Arauquita', 'department_id' =>81]);
        City::create(['name' => 'Arbeláez', 'department_id' =>25]);
        City::create(['name' => 'Arboleda [Berruecos]', 'department_id' =>52]);
        City::create(['name' => 'Arboledas', 'department_id' =>54]);
        City::create(['name' => 'Arboletes', 'department_id' =>5]);
        City::create(['name' => 'Arcabuco', 'department_id' =>15]);
        City::create(['name' => 'Arenal', 'department_id' =>13]);
        City::create(['name' => 'Argelia', 'department_id' =>5]);
        City::create(['name' => 'Argelia', 'department_id' =>19]);
        City::create(['name' => 'Argelia', 'department_id' =>76]);
        City::create(['name' => 'Ariguaní [El Difícil]', 'department_id' =>47]);
        City::create(['name' => 'Arjona', 'department_id' =>13]);
        City::create(['name' => 'Armenia', 'department_id' =>5]);
        City::create(['name' => 'Armenia', 'department_id' =>63]);
        City::create(['name' => 'Armero [Guayabal]', 'department_id' =>73]);
        City::create(['name' => 'Arroyohondo', 'department_id' =>13]);
        City::create(['name' => 'Astrea', 'department_id' =>20]);
        City::create(['name' => 'Ataco', 'department_id' =>73]);
        City::create(['name' => 'Atrato [Yuto]', 'department_id' =>27]);
        City::create(['name' => 'Ayapel', 'department_id' =>23]);
        City::create(['name' => 'Bagadó', 'department_id' =>27]);
        City::create(['name' => 'Bahía Solano [Mútis]', 'department_id' =>27]);
        City::create(['name' => 'Bajo Baudó [Pizarro]', 'department_id' =>27]);
        City::create(['name' => 'Balboa', 'department_id' =>19]);
        City::create(['name' => 'Balboa', 'department_id' =>66]);
        City::create(['name' => 'Baranoa', 'department_id' =>8]);
        City::create(['name' => 'Baraya', 'department_id' =>41]);
        City::create(['name' => 'Barbacoas', 'department_id' =>52]);
        City::create(['name' => 'Barbosa', 'department_id' =>5]);
        City::create(['name' => 'Barbosa', 'department_id' =>68]);
        City::create(['name' => 'Barichara', 'department_id' =>68]);
        City::create(['name' => 'Barranca de Upía', 'department_id' =>50]);
        City::create(['name' => 'Barrancabermeja', 'department_id' =>68]);
        City::create(['name' => 'Barrancas', 'department_id' =>44]);
        City::create(['name' => 'Barranco de Loba', 'department_id' =>13]);
        City::create(['name' => 'Barranquilla', 'department_id' =>8]);
        City::create(['name' => 'Becerríl', 'department_id' =>20]);
        City::create(['name' => 'Belalcázar', 'department_id' =>17]);
        City::create(['name' => 'Bello', 'department_id' =>5]);
        City::create(['name' => 'Belmira', 'department_id' =>5]);
        City::create(['name' => 'Beltrán', 'department_id' =>25]);
        City::create(['name' => 'Belén', 'department_id' =>15]);
        City::create(['name' => 'Belén', 'department_id' =>52]);
        City::create(['name' => 'Belén de Bajirá', 'department_id' =>27]);
        City::create(['name' => 'Belén de Umbría', 'department_id' =>66]);
        City::create(['name' => 'Belén de los Andaquíes', 'department_id' =>18]);
        City::create(['name' => 'Berbeo', 'department_id' =>15]);
        City::create(['name' => 'Betania', 'department_id' =>5]);
        City::create(['name' => 'Beteitiva', 'department_id' =>15]);
        City::create(['name' => 'Betulia', 'department_id' =>5]);
        City::create(['name' => 'Betulia', 'department_id' =>68]);
        City::create(['name' => 'Bituima', 'department_id' =>25]);
        City::create(['name' => 'Boavita', 'department_id' =>15]);
        City::create(['name' => 'Bochalema', 'department_id' =>54]);
        City::create(['name' => 'Bogotá D.C.', 'department_id' =>11]);
        City::create(['name' => 'Bojacá', 'department_id' =>25]);
        City::create(['name' => 'Bojayá [Bellavista]', 'department_id' =>27]);
        City::create(['name' => 'Bolívar', 'department_id' =>5]);
        City::create(['name' => 'Bolívar', 'department_id' =>19]);
        City::create(['name' => 'Bolívar', 'department_id' =>68]);
        City::create(['name' => 'Bolívar', 'department_id' =>76]);
        City::create(['name' => 'Bosconia', 'department_id' =>20]);
        City::create(['name' => 'Boyacá', 'department_id' =>15]);
        City::create(['name' => 'Briceño', 'department_id' =>5]);
        City::create(['name' => 'Briceño', 'department_id' =>15]);
        City::create(['name' => 'Bucaramanga', 'department_id' =>68]);
        City::create(['name' => 'Bucarasica', 'department_id' =>54]);
        City::create(['name' => 'Buenaventura', 'department_id' =>76]);
        City::create(['name' => 'Buenavista', 'department_id' =>15]);
        City::create(['name' => 'Buenavista', 'department_id' =>23]);
        City::create(['name' => 'Buenavista', 'department_id' =>63]);
        City::create(['name' => 'Buenavista', 'department_id' =>70]);
        City::create(['name' => 'Buenos Aires', 'department_id' =>19]);
        City::create(['name' => 'Buesaco', 'department_id' =>52]);
        City::create(['name' => 'Buga', 'department_id' =>76]);
        City::create(['name' => 'Bugalagrande', 'department_id' =>76]);
        City::create(['name' => 'Burítica', 'department_id' =>5]);
        City::create(['name' => 'Busbanza', 'department_id' =>15]);
        City::create(['name' => 'Cabrera', 'department_id' =>25]);
        City::create(['name' => 'Cabrera', 'department_id' =>68]);
        City::create(['name' => 'Cabuyaro', 'department_id' =>50]);
        City::create(['name' => 'Cachipay', 'department_id' =>25]);
        City::create(['name' => 'Caicedo', 'department_id' =>5]);
        City::create(['name' => 'Caicedonia', 'department_id' =>76]);
        City::create(['name' => 'Caimito', 'department_id' =>70]);
        City::create(['name' => 'Cajamarca', 'department_id' =>73]);
        City::create(['name' => 'Cajibío', 'department_id' =>19]);
        City::create(['name' => 'Cajicá', 'department_id' =>25]);
        City::create(['name' => 'Calamar', 'department_id' =>13]);
        City::create(['name' => 'Calamar', 'department_id' =>95]);
        City::create(['name' => 'Calarcá', 'department_id' =>63]);
        City::create(['name' => 'Caldas', 'department_id' =>5]);
        City::create(['name' => 'Caldas', 'department_id' =>15]);
        City::create(['name' => 'Caldono', 'department_id' =>19]);
        City::create(['name' => 'California', 'department_id' =>68]);
        City::create(['name' => 'Calima [Darién]', 'department_id' =>76]);
        City::create(['name' => 'Caloto', 'department_id' =>19]);
        City::create(['name' => 'Cali', 'department_id' =>76]);
        City::create(['name' => 'Campamento', 'department_id' =>5]);
        City::create(['name' => 'Campo de la Cruz', 'department_id' =>8]);
        City::create(['name' => 'Campoalegre', 'department_id' =>41]);
        City::create(['name' => 'Campohermoso', 'department_id' =>15]);
        City::create(['name' => 'Canalete', 'department_id' =>23]);
        City::create(['name' => 'Candelaria', 'department_id' =>8]);
        City::create(['name' => 'Candelaria', 'department_id' =>76]);
        City::create(['name' => 'Cantagallo', 'department_id' =>13]);
        City::create(['name' => 'Cantón de San Pablo', 'department_id' =>27]);
        City::create(['name' => 'Caparrapí', 'department_id' =>25]);
        City::create(['name' => 'Capitanejo', 'department_id' =>68]);
        City::create(['name' => 'Caracolí', 'department_id' =>5]);
        City::create(['name' => 'Caramanta', 'department_id' =>5]);
        City::create(['name' => 'Carcasí', 'department_id' =>68]);
        City::create(['name' => 'Carepa', 'department_id' =>5]);
        City::create(['name' => 'Carmen de Apicalá', 'department_id' =>73]);
        City::create(['name' => 'Carmen de Carupa', 'department_id' =>25]);
        City::create(['name' => 'Carmen de Viboral', 'department_id' =>5]);
        City::create(['name' => 'Carmen del Darién [CURBARADÓ]', 'department_id' =>27]);
        City::create(['name' => 'Carolina', 'department_id' =>5]);
        City::create(['name' => 'Cartagena', 'department_id' =>13]);
        City::create(['name' => 'Cartagena del Chairá', 'department_id' =>18]);
        City::create(['name' => 'Cartago', 'department_id' =>76]);
        City::create(['name' => 'Carurú', 'department_id' =>97]);
        City::create(['name' => 'Casabianca', 'department_id' =>73]);
        City::create(['name' => 'Castilla la Nueva', 'department_id' =>50]);
        City::create(['name' => 'Caucasia', 'department_id' =>5]);
        City::create(['name' => 'Cañasgordas', 'department_id' =>5]);
        City::create(['name' => 'Cepita', 'department_id' =>68]);
        City::create(['name' => 'Cereté', 'department_id' =>23]);
        City::create(['name' => 'Cerinza', 'department_id' =>15]);
        City::create(['name' => 'Cerrito', 'department_id' =>68]);
        City::create(['name' => 'Cerro San Antonio', 'department_id' =>47]);
        City::create(['name' => 'Chachaguí', 'department_id' =>52]);
        City::create(['name' => 'Chaguaní', 'department_id' =>25]);
        City::create(['name' => 'Chalán', 'department_id' =>70]);
        City::create(['name' => 'Chaparral', 'department_id' =>73]);
        City::create(['name' => 'Charalá', 'department_id' =>68]);
        City::create(['name' => 'Charta', 'department_id' =>68]);
        City::create(['name' => 'Chigorodó', 'department_id' =>5]);
        City::create(['name' => 'Chima', 'department_id' =>68]);
        City::create(['name' => 'Chimichagua', 'department_id' =>20]);
        City::create(['name' => 'Chimá', 'department_id' =>23]);
        City::create(['name' => 'Chinavita', 'department_id' =>15]);
        City::create(['name' => 'Chinchiná', 'department_id' =>17]);
        City::create(['name' => 'Chinácota', 'department_id' =>54]);
        City::create(['name' => 'Chinú', 'department_id' =>23]);
        City::create(['name' => 'Chipaque', 'department_id' =>25]);
        City::create(['name' => 'Chipatá', 'department_id' =>68]);
        City::create(['name' => 'Chiquinquirá', 'department_id' =>15]);
        City::create(['name' => 'Chiriguaná', 'department_id' =>20]);
        City::create(['name' => 'Chiscas', 'department_id' =>15]);
        City::create(['name' => 'Chita', 'department_id' =>15]);
        City::create(['name' => 'Chitagá', 'department_id' =>54]);
        City::create(['name' => 'Chitaraque', 'department_id' =>15]);
        City::create(['name' => 'Chivatá', 'department_id' =>15]);
        City::create(['name' => 'Chivolo', 'department_id' =>47]);
        City::create(['name' => 'Choachí', 'department_id' =>25]);
        City::create(['name' => 'Chocontá', 'department_id' =>25]);
        City::create(['name' => 'Chámeza', 'department_id' =>85]);
        City::create(['name' => 'Chía', 'department_id' =>25]);
        City::create(['name' => 'Chíquiza', 'department_id' =>15]);
        City::create(['name' => 'Chívor', 'department_id' =>15]);
        City::create(['name' => 'Cicuco', 'department_id' =>13]);
        City::create(['name' => 'Cimitarra', 'department_id' =>68]);
        City::create(['name' => 'Circasia', 'department_id' =>63]);
        City::create(['name' => 'Cisneros', 'department_id' =>5]);
        City::create(['name' => 'Ciénaga', 'department_id' =>15]);
        City::create(['name' => 'Ciénaga', 'department_id' =>47]);
        City::create(['name' => 'Ciénaga de Oro', 'department_id' =>23]);
        City::create(['name' => 'Clemencia', 'department_id' =>13]);
        City::create(['name' => 'Cocorná', 'department_id' =>5]);
        City::create(['name' => 'Coello', 'department_id' =>73]);
        City::create(['name' => 'Cogua', 'department_id' =>25]);
        City::create(['name' => 'Colombia', 'department_id' =>41]);
        City::create(['name' => 'Colosó [Ricaurte]', 'department_id' =>70]);
        City::create(['name' => 'Colón', 'department_id' =>86]);
        City::create(['name' => 'Colón [Génova]', 'department_id' =>52]);
        City::create(['name' => 'Concepción', 'department_id' =>5]);
        City::create(['name' => 'Concepción', 'department_id' =>68]);
        City::create(['name' => 'Concordia', 'department_id' =>5]);
        City::create(['name' => 'Concordia', 'department_id' =>47]);
        City::create(['name' => 'Condoto', 'department_id' =>27]);
        City::create(['name' => 'Confines', 'department_id' =>68]);
        City::create(['name' => 'Consaca', 'department_id' =>52]);
        City::create(['name' => 'Contadero', 'department_id' =>52]);
        City::create(['name' => 'Contratación', 'department_id' =>68]);
        City::create(['name' => 'Convención', 'department_id' =>54]);
        City::create(['name' => 'Copacabana', 'department_id' =>5]);
        City::create(['name' => 'Coper', 'department_id' =>15]);
        City::create(['name' => 'Cordobá', 'department_id' =>63]);
        City::create(['name' => 'Corinto', 'department_id' =>19]);
        City::create(['name' => 'Coromoro', 'department_id' =>68]);
        City::create(['name' => 'Corozal', 'department_id' =>70]);
        City::create(['name' => 'Corrales', 'department_id' =>15]);
        City::create(['name' => 'Cota', 'department_id' =>25]);
        City::create(['name' => 'Cotorra', 'department_id' =>23]);
        City::create(['name' => 'Covarachía', 'department_id' =>15]);
        City::create(['name' => 'Coveñas', 'department_id' =>70]);
        City::create(['name' => 'Coyaima', 'department_id' =>73]);
        City::create(['name' => 'Cravo Norte', 'department_id' =>81]);
        City::create(['name' => 'Cuaspud [Carlosama]', 'department_id' =>52]);
        City::create(['name' => 'Cubarral', 'department_id' =>50]);
        City::create(['name' => 'Cubará', 'department_id' =>15]);
        City::create(['name' => 'Cucaita', 'department_id' =>15]);
        City::create(['name' => 'Cucunubá', 'department_id' =>25]);
        City::create(['name' => 'Cucutilla', 'department_id' =>54]);
        City::create(['name' => 'Cuitiva', 'department_id' =>15]);
        City::create(['name' => 'Cumaral', 'department_id' =>50]);
        City::create(['name' => 'Cumaribo', 'department_id' =>99]);
        City::create(['name' => 'Cumbal', 'department_id' =>52]);
        City::create(['name' => 'Cumbitara', 'department_id' =>52]);
        City::create(['name' => 'Cunday', 'department_id' =>73]);
        City::create(['name' => 'Curillo', 'department_id' =>18]);
        City::create(['name' => 'Curití', 'department_id' =>68]);
        City::create(['name' => 'Curumaní', 'department_id' =>20]);
        City::create(['name' => 'Cáceres', 'department_id' =>5]);
        City::create(['name' => 'Cáchira', 'department_id' =>54]);
        City::create(['name' => 'Cácota', 'department_id' =>54]);
        City::create(['name' => 'Cáqueza', 'department_id' =>25]);
        City::create(['name' => 'Cértegui', 'department_id' =>27]);
        City::create(['name' => 'Cómbita', 'department_id' =>15]);
        City::create(['name' => 'Córdoba', 'department_id' =>13]);
        City::create(['name' => 'Córdoba', 'department_id' =>52]);
        City::create(['name' => 'Cúcuta', 'department_id' =>54]);
        City::create(['name' => 'Dabeiba', 'department_id' =>5]);
        City::create(['name' => 'Dagua', 'department_id' =>76]);
        City::create(['name' => 'Dibulla', 'department_id' =>44]);
        City::create(['name' => 'Distracción', 'department_id' =>44]);
        City::create(['name' => 'Dolores', 'department_id' =>73]);
        City::create(['name' => 'Don Matías', 'department_id' =>5]);
        City::create(['name' => 'Dos Quebradas', 'department_id' =>66]);
        City::create(['name' => 'Duitama', 'department_id' =>15]);
        City::create(['name' => 'Durania', 'department_id' =>54]);
        City::create(['name' => 'Ebéjico', 'department_id' =>5]);
        City::create(['name' => 'El Bagre', 'department_id' =>5]);
        City::create(['name' => 'El Banco', 'department_id' =>47]);
        City::create(['name' => 'El Cairo', 'department_id' =>76]);
        City::create(['name' => 'El Calvario', 'department_id' =>50]);
        City::create(['name' => 'El Carmen', 'department_id' =>54]);
        City::create(['name' => 'El Carmen', 'department_id' =>68]);
        City::create(['name' => 'El Carmen de Atrato', 'department_id' =>27]);
        City::create(['name' => 'El Carmen de Bolívar', 'department_id' =>13]);
        City::create(['name' => 'El Castillo', 'department_id' =>50]);
        City::create(['name' => 'El Cerrito', 'department_id' =>76]);
        City::create(['name' => 'El Charco', 'department_id' =>52]);
        City::create(['name' => 'El Cocuy', 'department_id' =>15]);
        City::create(['name' => 'El Colegio', 'department_id' =>25]);
        City::create(['name' => 'El Copey', 'department_id' =>20]);
        City::create(['name' => 'El Doncello', 'department_id' =>18]);
        City::create(['name' => 'El Dorado', 'department_id' =>50]);
        City::create(['name' => 'El Dovio', 'department_id' =>76]);
        City::create(['name' => 'El Espino', 'department_id' =>15]);
        City::create(['name' => 'El Guacamayo', 'department_id' =>68]);
        City::create(['name' => 'El Guamo', 'department_id' =>13]);
        City::create(['name' => 'El Molino', 'department_id' =>44]);
        City::create(['name' => 'El Paso', 'department_id' =>20]);
        City::create(['name' => 'El Paujil', 'department_id' =>18]);
        City::create(['name' => 'El Peñol', 'department_id' =>52]);
        City::create(['name' => 'El Peñon', 'department_id' =>13]);
        City::create(['name' => 'El Peñon', 'department_id' =>68]);
        City::create(['name' => 'El Peñón', 'department_id' =>25]);
        City::create(['name' => 'El Piñon', 'department_id' =>47]);
        City::create(['name' => 'El Playón', 'department_id' =>68]);
        City::create(['name' => 'El Retorno', 'department_id' =>95]);
        City::create(['name' => 'El Retén', 'department_id' =>47]);
        City::create(['name' => 'El Roble', 'department_id' =>70]);
        City::create(['name' => 'El Rosal', 'department_id' =>25]);
        City::create(['name' => 'El Rosario', 'department_id' =>52]);
        City::create(['name' => 'El Tablón de Gómez', 'department_id' =>52]);
        City::create(['name' => 'El Tambo', 'department_id' =>19]);
        City::create(['name' => 'El Tambo', 'department_id' =>52]);
        City::create(['name' => 'El Tarra', 'department_id' =>54]);
        City::create(['name' => 'El Zulia', 'department_id' =>54]);
        City::create(['name' => 'El Águila', 'department_id' =>76]);
        City::create(['name' => 'Elías', 'department_id' =>41]);
        City::create(['name' => 'Encino', 'department_id' =>68]);
        City::create(['name' => 'Enciso', 'department_id' =>68]);
        City::create(['name' => 'Entrerríos', 'department_id' =>5]);
        City::create(['name' => 'Envigado', 'department_id' =>5]);
        City::create(['name' => 'Espinal', 'department_id' =>73]);
        City::create(['name' => 'Facatativá', 'department_id' =>25]);
        City::create(['name' => 'Falan', 'department_id' =>73]);
        City::create(['name' => 'Filadelfia', 'department_id' =>17]);
        City::create(['name' => 'Filandia', 'department_id' =>63]);
        City::create(['name' => 'Firavitoba', 'department_id' =>15]);
        City::create(['name' => 'Flandes', 'department_id' =>73]);
        City::create(['name' => 'Florencia', 'department_id' =>18]);
        City::create(['name' => 'Florencia', 'department_id' =>19]);
        City::create(['name' => 'Floresta', 'department_id' =>15]);
        City::create(['name' => 'Florida', 'department_id' =>76]);
        City::create(['name' => 'Floridablanca', 'department_id' =>68]);
        City::create(['name' => 'Florián', 'department_id' =>68]);
        City::create(['name' => 'Fonseca', 'department_id' =>44]);
        City::create(['name' => 'Fortúl', 'department_id' =>81]);
        City::create(['name' => 'Fosca', 'department_id' =>25]);
        City::create(['name' => 'Francisco Pizarro', 'department_id' =>52]);
        City::create(['name' => 'Fredonia', 'department_id' =>5]);
        City::create(['name' => 'Fresno', 'department_id' =>73]);
        City::create(['name' => 'Frontino', 'department_id' =>5]);
        City::create(['name' => 'Fuente de Oro', 'department_id' =>50]);
        City::create(['name' => 'Fundación', 'department_id' =>47]);
        City::create(['name' => 'Funes', 'department_id' =>52]);
        City::create(['name' => 'Funza', 'department_id' =>25]);
        City::create(['name' => 'Fusagasugá', 'department_id' =>25]);
        City::create(['name' => 'Fómeque', 'department_id' =>25]);
        City::create(['name' => 'Fúquene', 'department_id' =>25]);
        City::create(['name' => 'Gachalá', 'department_id' =>25]);
        City::create(['name' => 'Gachancipá', 'department_id' =>25]);
        City::create(['name' => 'Gachantivá', 'department_id' =>15]);
        City::create(['name' => 'Gachetá', 'department_id' =>25]);
        City::create(['name' => 'Galapa', 'department_id' =>8]);
        City::create(['name' => 'Galeras [Nueva Granada]', 'department_id' =>70]);
        City::create(['name' => 'Galán', 'department_id' =>68]);
        City::create(['name' => 'Gama', 'department_id' =>25]);
        City::create(['name' => 'Gamarra', 'department_id' =>20]);
        City::create(['name' => 'Garagoa', 'department_id' =>15]);
        City::create(['name' => 'Garzón', 'department_id' =>41]);
        City::create(['name' => 'Gigante', 'department_id' =>41]);
        City::create(['name' => 'Ginebra', 'department_id' =>76]);
        City::create(['name' => 'Giraldo', 'department_id' =>5]);
        City::create(['name' => 'Girardot', 'department_id' =>25]);
        City::create(['name' => 'Girardota', 'department_id' =>5]);
        City::create(['name' => 'Girón', 'department_id' =>68]);
        City::create(['name' => 'Gonzalez', 'department_id' =>20]);
        City::create(['name' => 'Gramalote', 'department_id' =>54]);
        City::create(['name' => 'Granada', 'department_id' =>5]);
        City::create(['name' => 'Granada', 'department_id' =>25]);
        City::create(['name' => 'Granada', 'department_id' =>50]);
        City::create(['name' => 'Guaca', 'department_id' =>68]);
        City::create(['name' => 'Guacamayas', 'department_id' =>15]);
        City::create(['name' => 'Guacarí', 'department_id' =>76]);
        City::create(['name' => 'Guachavés', 'department_id' =>52]);
        City::create(['name' => 'Guachené', 'department_id' =>19]);
        City::create(['name' => 'Guachetá', 'department_id' =>25]);
        City::create(['name' => 'Guachucal', 'department_id' =>52]);
        City::create(['name' => 'Guadalupe', 'department_id' =>5]);
        City::create(['name' => 'Guadalupe', 'department_id' =>41]);
        City::create(['name' => 'Guadalupe', 'department_id' =>68]);
        City::create(['name' => 'Guaduas', 'department_id' =>25]);
        City::create(['name' => 'Guaitarilla', 'department_id' =>52]);
        City::create(['name' => 'Gualmatán', 'department_id' =>52]);
        City::create(['name' => 'Guamal', 'department_id' =>47]);
        City::create(['name' => 'Guamal', 'department_id' =>50]);
        City::create(['name' => 'Guamo', 'department_id' =>73]);
        City::create(['name' => 'Guapota', 'department_id' =>68]);
        City::create(['name' => 'Guapí', 'department_id' =>19]);
        City::create(['name' => 'Guaranda', 'department_id' =>70]);
        City::create(['name' => 'Guarne', 'department_id' =>5]);
        City::create(['name' => 'Guasca', 'department_id' =>25]);
        City::create(['name' => 'Guatapé', 'department_id' =>5]);
        City::create(['name' => 'Guataquí', 'department_id' =>25]);
        City::create(['name' => 'Guatavita', 'department_id' =>25]);
        City::create(['name' => 'Guateque', 'department_id' =>15]);
        City::create(['name' => 'Guavatá', 'department_id' =>68]);
        City::create(['name' => 'Guayabal de Siquima', 'department_id' =>25]);
        City::create(['name' => 'Guayabetal', 'department_id' =>25]);
        City::create(['name' => 'Guayatá', 'department_id' =>15]);
        City::create(['name' => 'Guepsa', 'department_id' =>68]);
        City::create(['name' => 'Guicán', 'department_id' =>15]);
        City::create(['name' => 'Gutiérrez', 'department_id' =>25]);
        City::create(['name' => 'Guática', 'department_id' =>66]);
        City::create(['name' => 'Gámbita', 'department_id' =>68]);
        City::create(['name' => 'Gámeza', 'department_id' =>15]);
        City::create(['name' => 'Génova', 'department_id' =>63]);
        City::create(['name' => 'Gómez Plata', 'department_id' =>5]);
        City::create(['name' => 'Hacarí', 'department_id' =>54]);
        City::create(['name' => 'Hatillo de Loba', 'department_id' =>13]);
        City::create(['name' => 'Hato', 'department_id' =>68]);
        City::create(['name' => 'Hato Corozal', 'department_id' =>85]);
        City::create(['name' => 'Hatonuevo', 'department_id' =>44]);
        City::create(['name' => 'Heliconia', 'department_id' =>5]);
        City::create(['name' => 'Herrán', 'department_id' =>54]);
        City::create(['name' => 'Herveo', 'department_id' =>73]);
        City::create(['name' => 'Hispania', 'department_id' =>5]);
        City::create(['name' => 'Hobo', 'department_id' =>41]);
        City::create(['name' => 'Honda', 'department_id' =>73]);
        City::create(['name' => 'Ibagué', 'department_id' =>73]);
        City::create(['name' => 'Icononzo', 'department_id' =>73]);
        City::create(['name' => 'Iles', 'department_id' =>52]);
        City::create(['name' => 'Imúes', 'department_id' =>52]);
        City::create(['name' => 'Inzá', 'department_id' =>19]);
        City::create(['name' => 'Inírida', 'department_id' =>94]);
        City::create(['name' => 'Ipiales', 'department_id' =>52]);
        City::create(['name' => 'Isnos', 'department_id' =>41]);
        City::create(['name' => 'Istmina', 'department_id' =>27]);
        City::create(['name' => 'Itagüí', 'department_id' =>5]);
        City::create(['name' => 'Ituango', 'department_id' =>5]);
        City::create(['name' => 'Izá', 'department_id' =>15]);
        City::create(['name' => 'Jambaló', 'department_id' =>19]);
        City::create(['name' => 'Jamundí', 'department_id' =>76]);
        City::create(['name' => 'Jardín', 'department_id' =>5]);
        City::create(['name' => 'Jenesano', 'department_id' =>15]);
        City::create(['name' => 'Jericó', 'department_id' =>5]);
        City::create(['name' => 'Jericó', 'department_id' =>15]);
        City::create(['name' => 'Jerusalén', 'department_id' =>25]);
        City::create(['name' => 'Jesús María', 'department_id' =>68]);
        City::create(['name' => 'Jordán', 'department_id' =>68]);
        City::create(['name' => 'Juan de Acosta', 'department_id' =>8]);
        City::create(['name' => 'Junín', 'department_id' =>25]);
        City::create(['name' => 'Juradó', 'department_id' =>27]);
        City::create(['name' => 'La Apartada y La Frontera', 'department_id' =>23]);
        City::create(['name' => 'La Argentina', 'department_id' =>41]);
        City::create(['name' => 'La Belleza', 'department_id' =>68]);
        City::create(['name' => 'La Calera', 'department_id' =>25]);
        City::create(['name' => 'La Capilla', 'department_id' =>15]);
        City::create(['name' => 'La Ceja', 'department_id' =>5]);
        City::create(['name' => 'La Celia', 'department_id' =>66]);
        City::create(['name' => 'La Cruz', 'department_id' =>52]);
        City::create(['name' => 'La Cumbre', 'department_id' =>76]);
        City::create(['name' => 'La Dorada', 'department_id' =>17]);
        City::create(['name' => 'La Esperanza', 'department_id' =>54]);
        City::create(['name' => 'La Estrella', 'department_id' =>5]);
        City::create(['name' => 'La Florida', 'department_id' =>52]);
        City::create(['name' => 'La Gloria', 'department_id' =>20]);
        City::create(['name' => 'La Jagua de Ibirico', 'department_id' =>20]);
        City::create(['name' => 'La Jagua del Pilar', 'department_id' =>44]);
        City::create(['name' => 'La Llanada', 'department_id' =>52]);
        City::create(['name' => 'La Macarena', 'department_id' =>50]);
        City::create(['name' => 'La Merced', 'department_id' =>17]);
        City::create(['name' => 'La Mesa', 'department_id' =>25]);
        City::create(['name' => 'La Montañita', 'department_id' =>18]);
        City::create(['name' => 'La Palma', 'department_id' =>25]);
        City::create(['name' => 'La Paz', 'department_id' =>68]);
        City::create(['name' => 'La Paz [Robles]', 'department_id' =>20]);
        City::create(['name' => 'La Peña', 'department_id' =>25]);
        City::create(['name' => 'La Pintada', 'department_id' =>5]);
        City::create(['name' => 'La Plata', 'department_id' =>41]);
        City::create(['name' => 'La Playa', 'department_id' =>54]);
        City::create(['name' => 'La Primavera', 'department_id' =>99]);
        City::create(['name' => 'La Salina', 'department_id' =>85]);
        City::create(['name' => 'La Sierra', 'department_id' =>19]);
        City::create(['name' => 'La Tebaida', 'department_id' =>63]);
        City::create(['name' => 'La Tola', 'department_id' =>52]);
        City::create(['name' => 'La Unión', 'department_id' =>5]);
        City::create(['name' => 'La Unión', 'department_id' =>52]);
        City::create(['name' => 'La Unión', 'department_id' =>70]);
        City::create(['name' => 'La Unión', 'department_id' =>76]);
        City::create(['name' => 'La Uvita', 'department_id' =>15]);
        City::create(['name' => 'La Vega', 'department_id' =>19]);
        City::create(['name' => 'La Vega', 'department_id' =>25]);
        City::create(['name' => 'La Victoria', 'department_id' =>15]);
        City::create(['name' => 'La Victoria', 'department_id' =>17]);
        City::create(['name' => 'La Victoria', 'department_id' =>76]);
        City::create(['name' => 'La Virginia', 'department_id' =>66]);
        City::create(['name' => 'Labateca', 'department_id' =>54]);
        City::create(['name' => 'Labranzagrande', 'department_id' =>15]);
        City::create(['name' => 'Landázuri', 'department_id' =>68]);
        City::create(['name' => 'Lebrija', 'department_id' =>68]);
        City::create(['name' => 'Leiva', 'department_id' =>52]);
        City::create(['name' => 'Lejanías', 'department_id' =>50]);
        City::create(['name' => 'Lenguazaque', 'department_id' =>25]);
        City::create(['name' => 'Leticia', 'department_id' =>91]);
        City::create(['name' => 'Liborina', 'department_id' =>5]);
        City::create(['name' => 'Linares', 'department_id' =>52]);
        City::create(['name' => 'Lloró', 'department_id' =>27]);
        City::create(['name' => 'Lorica', 'department_id' =>23]);
        City::create(['name' => 'Los Córdobas', 'department_id' =>23]);
        City::create(['name' => 'Los Palmitos', 'department_id' =>70]);
        City::create(['name' => 'Los Patios', 'department_id' =>54]);
        City::create(['name' => 'Los Santos', 'department_id' =>68]);
        City::create(['name' => 'Lourdes', 'department_id' =>54]);
        City::create(['name' => 'Luruaco', 'department_id' =>8]);
        City::create(['name' => 'Lérida', 'department_id' =>73]);
        City::create(['name' => 'Líbano', 'department_id' =>73]);
        City::create(['name' => 'López [Micay]', 'department_id' =>19]);
        City::create(['name' => 'Macanal', 'department_id' =>15]);
        City::create(['name' => 'Macaravita', 'department_id' =>68]);
        City::create(['name' => 'Maceo', 'department_id' =>5]);
        City::create(['name' => 'Machetá', 'department_id' =>25]);
        City::create(['name' => 'Madrid', 'department_id' =>25]);
        City::create(['name' => 'Magangué', 'department_id' =>13]);
        City::create(['name' => 'Magüi [Payán]', 'department_id' =>52]);
        City::create(['name' => 'Mahates', 'department_id' =>13]);
        City::create(['name' => 'Maicao', 'department_id' =>44]);
        City::create(['name' => 'Majagual', 'department_id' =>70]);
        City::create(['name' => 'Malambo', 'department_id' =>8]);
        City::create(['name' => 'Mallama [Piedrancha]', 'department_id' =>52]);
        City::create(['name' => 'Manatí', 'department_id' =>8]);
        City::create(['name' => 'Manaure', 'department_id' =>44]);
        City::create(['name' => 'Manaure Balcón del Cesar', 'department_id' =>20]);
        City::create(['name' => 'Manizales', 'department_id' =>17]);
        City::create(['name' => 'Manta', 'department_id' =>25]);
        City::create(['name' => 'Manzanares', 'department_id' =>17]);
        City::create(['name' => 'Maní', 'department_id' =>85]);
        City::create(['name' => 'Mapiripan', 'department_id' =>50]);
        City::create(['name' => 'Margarita', 'department_id' =>13]);
        City::create(['name' => 'Marinilla', 'department_id' =>5]);
        City::create(['name' => 'Maripí', 'department_id' =>15]);
        City::create(['name' => 'Mariquita', 'department_id' =>73]);
        City::create(['name' => 'Marmato', 'department_id' =>17]);
        City::create(['name' => 'Marquetalia', 'department_id' =>17]);
        City::create(['name' => 'Marsella', 'department_id' =>66]);
        City::create(['name' => 'Marulanda', 'department_id' =>17]);
        City::create(['name' => 'María la Baja', 'department_id' =>13]);
        City::create(['name' => 'Matanza', 'department_id' =>68]);
        City::create(['name' => 'Medellín', 'department_id' =>5]);
        City::create(['name' => 'Medina', 'department_id' =>25]);
        City::create(['name' => 'Medio Atrato', 'department_id' =>27]);
        City::create(['name' => 'Medio Baudó', 'department_id' =>27]);
        City::create(['name' => 'Medio San Juan [ANDAGOYA]', 'department_id' =>27]);
        City::create(['name' => 'Melgar', 'department_id' =>73]);
        City::create(['name' => 'Mercaderes', 'department_id' =>19]);
        City::create(['name' => 'Mesetas', 'department_id' =>50]);
        City::create(['name' => 'Milán', 'department_id' =>18]);
        City::create(['name' => 'Miraflores', 'department_id' =>15]);
        City::create(['name' => 'Miraflores', 'department_id' =>95]);
        City::create(['name' => 'Miranda', 'department_id' =>19]);
        City::create(['name' => 'Mistrató', 'department_id' =>66]);
        City::create(['name' => 'Mitú', 'department_id' =>97]);
        City::create(['name' => 'Mocoa', 'department_id' =>86]);
        City::create(['name' => 'Mogotes', 'department_id' =>68]);
        City::create(['name' => 'Molagavita', 'department_id' =>68]);
        City::create(['name' => 'Momil', 'department_id' =>23]);
        City::create(['name' => 'Mompós', 'department_id' =>13]);
        City::create(['name' => 'Mongua', 'department_id' =>15]);
        City::create(['name' => 'Monguí', 'department_id' =>15]);
        City::create(['name' => 'Moniquirá', 'department_id' =>15]);
        City::create(['name' => 'Montebello', 'department_id' =>5]);
        City::create(['name' => 'Montecristo', 'department_id' =>13]);
        City::create(['name' => 'Montelíbano', 'department_id' =>23]);
        City::create(['name' => 'Montenegro', 'department_id' =>63]);
        City::create(['name' => 'Monteria', 'department_id' =>23]);
        City::create(['name' => 'Monterrey', 'department_id' =>85]);
        City::create(['name' => 'Morales', 'department_id' =>13]);
        City::create(['name' => 'Morales', 'department_id' =>19]);
        City::create(['name' => 'Morelia', 'department_id' =>18]);
        City::create(['name' => 'Morroa', 'department_id' =>70]);
        City::create(['name' => 'Mosquera', 'department_id' =>25]);
        City::create(['name' => 'Mosquera', 'department_id' =>52]);
        City::create(['name' => 'Motavita', 'department_id' =>15]);
        City::create(['name' => 'Moñitos', 'department_id' =>23]);
        City::create(['name' => 'Murillo', 'department_id' =>73]);
        City::create(['name' => 'Murindó', 'department_id' =>5]);
        City::create(['name' => 'Mutatá', 'department_id' =>5]);
        City::create(['name' => 'Mutiscua', 'department_id' =>54]);
        City::create(['name' => 'Muzo', 'department_id' =>15]);
        City::create(['name' => 'Málaga', 'department_id' =>68]);
        City::create(['name' => 'Nariño', 'department_id' =>5]);
        City::create(['name' => 'Nariño', 'department_id' =>25]);
        City::create(['name' => 'Nariño', 'department_id' =>52]);
        City::create(['name' => 'Natagaima', 'department_id' =>73]);
        City::create(['name' => 'Nechí', 'department_id' =>5]);
        City::create(['name' => 'Necoclí', 'department_id' =>5]);
        City::create(['name' => 'Neira', 'department_id' =>17]);
        City::create(['name' => 'Neiva', 'department_id' =>41]);
        City::create(['name' => 'Nemocón', 'department_id' =>25]);
        City::create(['name' => 'Nilo', 'department_id' =>25]);
        City::create(['name' => 'Nimaima', 'department_id' =>25]);
        City::create(['name' => 'Nobsa', 'department_id' =>15]);
        City::create(['name' => 'Nocaima', 'department_id' =>25]);
        City::create(['name' => 'Norcasia', 'department_id' =>17]);
        City::create(['name' => 'Norosí', 'department_id' =>13]);
        City::create(['name' => 'Novita', 'department_id' =>27]);
        City::create(['name' => 'Nueva Granada', 'department_id' =>47]);
        City::create(['name' => 'Nuevo Colón', 'department_id' =>15]);
        City::create(['name' => 'Nunchía', 'department_id' =>85]);
        City::create(['name' => 'Nuquí', 'department_id' =>27]);
        City::create(['name' => 'Nátaga', 'department_id' =>41]);
        City::create(['name' => 'Obando', 'department_id' =>76]);
        City::create(['name' => 'Ocamonte', 'department_id' =>68]);
        City::create(['name' => 'Ocaña', 'department_id' =>54]);
        City::create(['name' => 'Oiba', 'department_id' =>68]);
        City::create(['name' => 'Oicatá', 'department_id' =>15]);
        City::create(['name' => 'Olaya', 'department_id' =>5]);
        City::create(['name' => 'Olaya Herrera', 'department_id' =>52]);
        City::create(['name' => 'Onzaga', 'department_id' =>68]);
        City::create(['name' => 'Oporapa', 'department_id' =>41]);
        City::create(['name' => 'Orito', 'department_id' =>86]);
        City::create(['name' => 'Orocué', 'department_id' =>85]);
        City::create(['name' => 'Ortega', 'department_id' =>73]);
        City::create(['name' => 'Ospina', 'department_id' =>52]);
        City::create(['name' => 'Otanche', 'department_id' =>15]);
        City::create(['name' => 'Ovejas', 'department_id' =>70]);
        City::create(['name' => 'Pachavita', 'department_id' =>15]);
        City::create(['name' => 'Pacho', 'department_id' =>25]);
        City::create(['name' => 'Padilla', 'department_id' =>19]);
        City::create(['name' => 'Paicol', 'department_id' =>41]);
        City::create(['name' => 'Pailitas', 'department_id' =>20]);
        City::create(['name' => 'Paime', 'department_id' =>25]);
        City::create(['name' => 'Paipa', 'department_id' =>15]);
        City::create(['name' => 'Pajarito', 'department_id' =>15]);
        City::create(['name' => 'Palermo', 'department_id' =>41]);
        City::create(['name' => 'Palestina', 'department_id' =>17]);
        City::create(['name' => 'Palestina', 'department_id' =>41]);
        City::create(['name' => 'Palmar', 'department_id' =>68]);
        City::create(['name' => 'Palmar de Varela', 'department_id' =>8]);
        City::create(['name' => 'Palmas del Socorro', 'department_id' =>68]);
        City::create(['name' => 'Palmira', 'department_id' =>76]);
        City::create(['name' => 'Palmito', 'department_id' =>70]);
        City::create(['name' => 'Palocabildo', 'department_id' =>73]);
        City::create(['name' => 'Pamplona', 'department_id' =>54]);
        City::create(['name' => 'Pamplonita', 'department_id' =>54]);
        City::create(['name' => 'Pandi', 'department_id' =>25]);
        City::create(['name' => 'Panqueba', 'department_id' =>15]);
        City::create(['name' => 'Paratebueno', 'department_id' =>25]);
        City::create(['name' => 'Pasca', 'department_id' =>25]);
        City::create(['name' => 'Patía [El Bordo]', 'department_id' =>19]);
        City::create(['name' => 'Pauna', 'department_id' =>15]);
        City::create(['name' => 'Paya', 'department_id' =>15]);
        City::create(['name' => 'Paz de Ariporo', 'department_id' =>85]);
        City::create(['name' => 'Paz de Río', 'department_id' =>15]);
        City::create(['name' => 'Pedraza', 'department_id' =>47]);
        City::create(['name' => 'Pelaya', 'department_id' =>20]);
        City::create(['name' => 'Pensilvania', 'department_id' =>17]);
        City::create(['name' => 'Peque', 'department_id' =>5]);
        City::create(['name' => 'Pereira', 'department_id' =>66]);
        City::create(['name' => 'Pesca', 'department_id' =>15]);
        City::create(['name' => 'Peñol', 'department_id' =>5]);
        City::create(['name' => 'Piamonte', 'department_id' =>19]);
        City::create(['name' => 'Pie de Cuesta', 'department_id' =>68]);
        City::create(['name' => 'Piedras', 'department_id' =>73]);
        City::create(['name' => 'Piendamó', 'department_id' =>19]);
        City::create(['name' => 'Pijao', 'department_id' =>63]);
        City::create(['name' => 'Pijiño', 'department_id' =>47]);
        City::create(['name' => 'Pinchote', 'department_id' =>68]);
        City::create(['name' => 'Pinillos', 'department_id' =>13]);
        City::create(['name' => 'Piojo', 'department_id' =>8]);
        City::create(['name' => 'Pisva', 'department_id' =>15]);
        City::create(['name' => 'Pital', 'department_id' =>41]);
        City::create(['name' => 'Pitalito', 'department_id' =>41]);
        City::create(['name' => 'Pivijay', 'department_id' =>47]);
        City::create(['name' => 'Planadas', 'department_id' =>73]);
        City::create(['name' => 'Planeta Rica', 'department_id' =>23]);
        City::create(['name' => 'Plato', 'department_id' =>47]);
        City::create(['name' => 'Policarpa', 'department_id' =>52]);
        City::create(['name' => 'Polonuevo', 'department_id' =>8]);
        City::create(['name' => 'Ponedera', 'department_id' =>8]);
        City::create(['name' => 'Popayán', 'department_id' =>19]);
        City::create(['name' => 'Pore', 'department_id' =>85]);
        City::create(['name' => 'Potosí', 'department_id' =>52]);
        City::create(['name' => 'Pradera', 'department_id' =>76]);
        City::create(['name' => 'Prado', 'department_id' =>73]);
        City::create(['name' => 'Providencia', 'department_id' =>52]);
        City::create(['name' => 'Providencia', 'department_id' =>88]);
        City::create(['name' => 'Pueblo Bello', 'department_id' =>20]);
        City::create(['name' => 'Pueblo Nuevo', 'department_id' =>23]);
        City::create(['name' => 'Pueblo Rico', 'department_id' =>66]);
        City::create(['name' => 'Pueblorrico', 'department_id' =>5]);
        City::create(['name' => 'Puebloviejo', 'department_id' =>47]);
        City::create(['name' => 'Puente Nacional', 'department_id' =>68]);
        City::create(['name' => 'Puerres', 'department_id' =>52]);
        City::create(['name' => 'Puerto Asís', 'department_id' =>86]);
        City::create(['name' => 'Puerto Berrío', 'department_id' =>5]);
        City::create(['name' => 'Puerto Boyacá', 'department_id' =>15]);
        City::create(['name' => 'Puerto Caicedo', 'department_id' =>86]);
        City::create(['name' => 'Puerto Carreño', 'department_id' =>99]);
        City::create(['name' => 'Puerto Colombia', 'department_id' =>8]);
        City::create(['name' => 'Puerto Concordia', 'department_id' =>50]);
        City::create(['name' => 'Puerto Escondido', 'department_id' =>23]);
        City::create(['name' => 'Puerto Gaitán', 'department_id' =>50]);
        City::create(['name' => 'Puerto Guzmán', 'department_id' =>86]);
        City::create(['name' => 'Puerto Leguízamo', 'department_id' =>86]);
        City::create(['name' => 'Puerto Libertador', 'department_id' =>23]);
        City::create(['name' => 'Puerto Lleras', 'department_id' =>50]);
        City::create(['name' => 'Puerto López', 'department_id' =>50]);
        City::create(['name' => 'Puerto Nare', 'department_id' =>5]);
        City::create(['name' => 'Puerto Nariño', 'department_id' =>91]);
        City::create(['name' => 'Puerto Parra', 'department_id' =>68]);
        City::create(['name' => 'Puerto Rico', 'department_id' =>18]);
        City::create(['name' => 'Puerto Rico', 'department_id' =>50]);
        City::create(['name' => 'Puerto Rondón', 'department_id' =>81]);
        City::create(['name' => 'Puerto Salgar', 'department_id' =>25]);
        City::create(['name' => 'Puerto Santander', 'department_id' =>54]);
        City::create(['name' => 'Puerto Tejada', 'department_id' =>19]);
        City::create(['name' => 'Puerto Triunfo', 'department_id' =>5]);
        City::create(['name' => 'Puerto Wilches', 'department_id' =>68]);
        City::create(['name' => 'Pulí', 'department_id' =>25]);
        City::create(['name' => 'Pupiales', 'department_id' =>52]);
        City::create(['name' => 'Puracé [Coconuco]', 'department_id' =>19]);
        City::create(['name' => 'Purificación', 'department_id' =>73]);
        City::create(['name' => 'Purísima', 'department_id' =>23]);
        City::create(['name' => 'Pácora', 'department_id' =>17]);
        City::create(['name' => 'Páez', 'department_id' =>15]);
        City::create(['name' => 'Páez [Belalcazar]', 'department_id' =>19]);
        City::create(['name' => 'Páramo', 'department_id' =>68]);
        City::create(['name' => 'Quebradanegra', 'department_id' =>25]);
        City::create(['name' => 'Quetame', 'department_id' =>25]);
        City::create(['name' => 'Quibdó', 'department_id' =>27]);
        City::create(['name' => 'Quimbaya', 'department_id' =>63]);
        City::create(['name' => 'Quinchía', 'department_id' =>66]);
        City::create(['name' => 'Quipama', 'department_id' =>15]);
        City::create(['name' => 'Quipile', 'department_id' =>25]);
        City::create(['name' => 'Ragonvalia', 'department_id' =>54]);
        City::create(['name' => 'Ramiriquí', 'department_id' =>15]);
        City::create(['name' => 'Recetor', 'department_id' =>85]);
        City::create(['name' => 'Regidor', 'department_id' =>13]);
        City::create(['name' => 'Remedios', 'department_id' =>5]);
        City::create(['name' => 'Remolino', 'department_id' =>47]);
        City::create(['name' => 'Repelón', 'department_id' =>8]);
        City::create(['name' => 'Restrepo', 'department_id' =>50]);
        City::create(['name' => 'Restrepo', 'department_id' =>76]);
        City::create(['name' => 'Retiro', 'department_id' =>5]);
        City::create(['name' => 'Ricaurte', 'department_id' =>25]);
        City::create(['name' => 'Ricaurte', 'department_id' =>52]);
        City::create(['name' => 'Rio Negro', 'department_id' =>68]);
        City::create(['name' => 'Rioblanco', 'department_id' =>73]);
        City::create(['name' => 'Riofrío', 'department_id' =>76]);
        City::create(['name' => 'Riohacha', 'department_id' =>44]);
        City::create(['name' => 'Risaralda', 'department_id' =>17]);
        City::create(['name' => 'Rivera', 'department_id' =>41]);
        City::create(['name' => 'Roberto Payán [San José]', 'department_id' =>52]);
        City::create(['name' => 'Roldanillo', 'department_id' =>76]);
        City::create(['name' => 'Roncesvalles', 'department_id' =>73]);
        City::create(['name' => 'Rondón', 'department_id' =>15]);
        City::create(['name' => 'Rosas', 'department_id' =>19]);
        City::create(['name' => 'Rovira', 'department_id' =>73]);
        City::create(['name' => 'Ráquira', 'department_id' =>15]);
        City::create(['name' => 'Río Iró', 'department_id' =>27]);
        City::create(['name' => 'Río Quito', 'department_id' =>27]);
        City::create(['name' => 'Río Sucio', 'department_id' =>17]);
        City::create(['name' => 'Río Viejo', 'department_id' =>13]);
        City::create(['name' => 'Río de oro', 'department_id' =>20]);
        City::create(['name' => 'Ríonegro', 'department_id' =>5]);
        City::create(['name' => 'Ríosucio', 'department_id' =>27]);
        City::create(['name' => 'Sabana de Torres', 'department_id' =>68]);
        City::create(['name' => 'Sabanagrande', 'department_id' =>8]);
        City::create(['name' => 'Sabanalarga', 'department_id' =>5]);
        City::create(['name' => 'Sabanalarga', 'department_id' =>8]);
        City::create(['name' => 'Sabanalarga', 'department_id' =>85]);
        City::create(['name' => 'Sabanas de San Angel [SAN ANGEL]', 'department_id' =>47]);
        City::create(['name' => 'Sabaneta', 'department_id' =>5]);
        City::create(['name' => 'Saboyá', 'department_id' =>15]);
        City::create(['name' => 'Sahagún', 'department_id' =>23]);
        City::create(['name' => 'Saladoblanco', 'department_id' =>41]);
        City::create(['name' => 'Salamina', 'department_id' =>17]);
        City::create(['name' => 'Salamina', 'department_id' =>47]);
        City::create(['name' => 'Salazar', 'department_id' =>54]);
        City::create(['name' => 'Saldaña', 'department_id' =>73]);
        City::create(['name' => 'Salento', 'department_id' =>63]);
        City::create(['name' => 'Salgar', 'department_id' =>5]);
        City::create(['name' => 'Samacá', 'department_id' =>15]);
        City::create(['name' => 'Samaniego', 'department_id' =>52]);
        City::create(['name' => 'Samaná', 'department_id' =>17]);
        City::create(['name' => 'Sampués', 'department_id' =>70]);
        City::create(['name' => 'San Agustín', 'department_id' =>41]);
        City::create(['name' => 'San Alberto', 'department_id' =>20]);
        City::create(['name' => 'San Andrés', 'department_id' =>68]);
        City::create(['name' => 'San Andrés Sotavento', 'department_id' =>23]);
        City::create(['name' => 'San Andrés de Cuerquía', 'department_id' =>5]);
        City::create(['name' => 'San Antero', 'department_id' =>23]);
        City::create(['name' => 'San Antonio', 'department_id' =>73]);
        City::create(['name' => 'San Antonio de Tequendama', 'department_id' =>25]);
        City::create(['name' => 'San Benito', 'department_id' =>68]);
        City::create(['name' => 'San Benito Abad', 'department_id' =>70]);
        City::create(['name' => 'San Bernardo', 'department_id' =>25]);
        City::create(['name' => 'San Bernardo', 'department_id' =>52]);
        City::create(['name' => 'San Bernardo del Viento', 'department_id' =>23]);
        City::create(['name' => 'San Calixto', 'department_id' =>54]);
        City::create(['name' => 'San Carlos', 'department_id' =>5]);
        City::create(['name' => 'San Carlos', 'department_id' =>23]);
        City::create(['name' => 'San Carlos de Guaroa', 'department_id' =>50]);
        City::create(['name' => 'San Cayetano', 'department_id' =>25]);
        City::create(['name' => 'San Cayetano', 'department_id' =>54]);
        City::create(['name' => 'San Cristobal', 'department_id' =>13]);
        City::create(['name' => 'San Diego', 'department_id' =>20]);
        City::create(['name' => 'San Eduardo', 'department_id' =>15]);
        City::create(['name' => 'San Estanislao', 'department_id' =>13]);
        City::create(['name' => 'San Fernando', 'department_id' =>13]);
        City::create(['name' => 'San Francisco', 'department_id' =>5]);
        City::create(['name' => 'San Francisco', 'department_id' =>25]);
        City::create(['name' => 'San Francisco', 'department_id' =>86]);
        City::create(['name' => 'San Gíl', 'department_id' =>68]);
        City::create(['name' => 'San Jacinto', 'department_id' =>13]);
        City::create(['name' => 'San Jacinto del Cauca', 'department_id' =>13]);
        City::create(['name' => 'San Jerónimo', 'department_id' =>5]);
        City::create(['name' => 'San Joaquín', 'department_id' =>68]);
        City::create(['name' => 'San José', 'department_id' =>17]);
        City::create(['name' => 'San José de Miranda', 'department_id' =>68]);
        City::create(['name' => 'San José de Montaña', 'department_id' =>5]);
        City::create(['name' => 'San José de Pare', 'department_id' =>15]);
        City::create(['name' => 'San José de Uré', 'department_id' =>23]);
        City::create(['name' => 'San José del Fragua', 'department_id' =>18]);
        City::create(['name' => 'San José del Guaviare', 'department_id' =>95]);
        City::create(['name' => 'San José del Palmar', 'department_id' =>27]);
        City::create(['name' => 'San Juan de Arama', 'department_id' =>50]);
        City::create(['name' => 'San Juan de Betulia', 'department_id' =>70]);
        City::create(['name' => 'San Juan de Nepomuceno', 'department_id' =>13]);
        City::create(['name' => 'San Juan de Pasto', 'department_id' =>52]);
        City::create(['name' => 'San Juan de Río Seco', 'department_id' =>25]);
        City::create(['name' => 'San Juan de Urabá', 'department_id' =>5]);
        City::create(['name' => 'San Juan del Cesar', 'department_id' =>44]);
        City::create(['name' => 'San Juanito', 'department_id' =>50]);
        City::create(['name' => 'San Lorenzo', 'department_id' =>52]);
        City::create(['name' => 'San Luis', 'department_id' =>73]);
        City::create(['name' => 'San Luís', 'department_id' =>5]);
        City::create(['name' => 'San Luís de Gaceno', 'department_id' =>15]);
        City::create(['name' => 'San Luís de Palenque', 'department_id' =>85]);
        City::create(['name' => 'San Marcos', 'department_id' =>70]);
        City::create(['name' => 'San Martín', 'department_id' =>20]);
        City::create(['name' => 'San Martín', 'department_id' =>50]);
        City::create(['name' => 'San Martín de Loba', 'department_id' =>13]);
        City::create(['name' => 'San Mateo', 'department_id' =>15]);
        City::create(['name' => 'San Miguel', 'department_id' =>68]);
        City::create(['name' => 'San Miguel', 'department_id' =>86]);
        City::create(['name' => 'San Miguel de Sema', 'department_id' =>15]);
        City::create(['name' => 'San Onofre', 'department_id' =>70]);
        City::create(['name' => 'San Pablo', 'department_id' =>13]);
        City::create(['name' => 'San Pablo', 'department_id' =>52]);
        City::create(['name' => 'San Pablo de Borbur', 'department_id' =>15]);
        City::create(['name' => 'San Pedro', 'department_id' =>5]);
        City::create(['name' => 'San Pedro', 'department_id' =>70]);
        City::create(['name' => 'San Pedro', 'department_id' =>76]);
        City::create(['name' => 'San Pedro de Cartago', 'department_id' =>52]);
        City::create(['name' => 'San Pedro de Urabá', 'department_id' =>5]);
        City::create(['name' => 'San Pelayo', 'department_id' =>23]);
        City::create(['name' => 'San Rafael', 'department_id' =>5]);
        City::create(['name' => 'San Roque', 'department_id' =>5]);
        City::create(['name' => 'San Sebastián', 'department_id' =>19]);
        City::create(['name' => 'San Sebastián de Buenavista', 'department_id' =>47]);
        City::create(['name' => 'San Vicente', 'department_id' =>5]);
        City::create(['name' => 'San Vicente del Caguán', 'department_id' =>18]);
        City::create(['name' => 'San Vicente del Chucurí', 'department_id' =>68]);
        City::create(['name' => 'San Zenón', 'department_id' =>47]);
        City::create(['name' => 'Sandoná', 'department_id' =>52]);
        City::create(['name' => 'Santa Ana', 'department_id' =>47]);
        City::create(['name' => 'Santa Bárbara', 'department_id' =>5]);
        City::create(['name' => 'Santa Bárbara', 'department_id' =>68]);
        City::create(['name' => 'Santa Bárbara [Iscuandé]', 'department_id' =>52]);
        City::create(['name' => 'Santa Bárbara de Pinto', 'department_id' =>47]);
        City::create(['name' => 'Santa Catalina', 'department_id' =>13]);
        City::create(['name' => 'Santa Fé de Antioquia', 'department_id' =>5]);
        City::create(['name' => 'Santa Genoveva de Docorodó', 'department_id' =>27]);
        City::create(['name' => 'Santa Helena del Opón', 'department_id' =>68]);
        City::create(['name' => 'Santa Isabel', 'department_id' =>73]);
        City::create(['name' => 'Santa Lucía', 'department_id' =>8]);
        City::create(['name' => 'Santa Marta', 'department_id' =>47]);
        City::create(['name' => 'Santa María', 'department_id' =>15]);
        City::create(['name' => 'Santa María', 'department_id' =>41]);
        City::create(['name' => 'Santa Rosa', 'department_id' =>13]);
        City::create(['name' => 'Santa Rosa', 'department_id' =>19]);
        City::create(['name' => 'Santa Rosa de Cabal', 'department_id' =>66]);
        City::create(['name' => 'Santa Rosa de Osos', 'department_id' =>5]);
        City::create(['name' => 'Santa Rosa de Viterbo', 'department_id' =>15]);
        City::create(['name' => 'Santa Rosa del Sur', 'department_id' =>13]);
        City::create(['name' => 'Santa Rosalía', 'department_id' =>99]);
        City::create(['name' => 'Santa Sofía', 'department_id' =>15]);
        City::create(['name' => 'Santana', 'department_id' =>15]);
        City::create(['name' => 'Santander de Quilichao', 'department_id' =>19]);
        City::create(['name' => 'Santiago', 'department_id' =>54]);
        City::create(['name' => 'Santiago', 'department_id' =>86]);
        City::create(['name' => 'Santo Domingo', 'department_id' =>5]);
        City::create(['name' => 'Santo Tomás', 'department_id' =>8]);
        City::create(['name' => 'Santuario', 'department_id' =>5]);
        City::create(['name' => 'Santuario', 'department_id' =>66]);
        City::create(['name' => 'Sapuyes', 'department_id' =>52]);
        City::create(['name' => 'Saravena', 'department_id' =>81]);
        City::create(['name' => 'Sardinata', 'department_id' =>54]);
        City::create(['name' => 'Sasaima', 'department_id' =>25]);
        City::create(['name' => 'Sativanorte', 'department_id' =>15]);
        City::create(['name' => 'Sativasur', 'department_id' =>15]);
        City::create(['name' => 'Segovia', 'department_id' =>5]);
        City::create(['name' => 'Sesquilé', 'department_id' =>25]);
        City::create(['name' => 'Sevilla', 'department_id' =>76]);
        City::create(['name' => 'Siachoque', 'department_id' =>15]);
        City::create(['name' => 'Sibaté', 'department_id' =>25]);
        City::create(['name' => 'Sibundoy', 'department_id' =>86]);
        City::create(['name' => 'Silos', 'department_id' =>54]);
        City::create(['name' => 'Silvania', 'department_id' =>25]);
        City::create(['name' => 'Silvia', 'department_id' =>19]);
        City::create(['name' => 'Simacota', 'department_id' =>68]);
        City::create(['name' => 'Simijaca', 'department_id' =>25]);
        City::create(['name' => 'Simití', 'department_id' =>13]);
        City::create(['name' => 'Sincelejo', 'department_id' =>70]);
        City::create(['name' => 'Sincé', 'department_id' =>70]);
        City::create(['name' => 'Sipí', 'department_id' =>27]);
        City::create(['name' => 'Sitionuevo', 'department_id' =>47]);
        City::create(['name' => 'Soacha', 'department_id' =>25]);
        City::create(['name' => 'Soatá', 'department_id' =>15]);
        City::create(['name' => 'Socha', 'department_id' =>15]);
        City::create(['name' => 'Socorro', 'department_id' =>68]);
        City::create(['name' => 'Socotá', 'department_id' =>15]);
        City::create(['name' => 'Sogamoso', 'department_id' =>15]);
        City::create(['name' => 'Solano', 'department_id' =>18]);
        City::create(['name' => 'Soledad', 'department_id' =>8]);
        City::create(['name' => 'Solita', 'department_id' =>18]);
        City::create(['name' => 'Somondoco', 'department_id' =>15]);
        City::create(['name' => 'Sonsón', 'department_id' =>5]);
        City::create(['name' => 'Sopetrán', 'department_id' =>5]);
        City::create(['name' => 'Soplaviento', 'department_id' =>13]);
        City::create(['name' => 'Sopó', 'department_id' =>25]);
        City::create(['name' => 'Sora', 'department_id' =>15]);
        City::create(['name' => 'Soracá', 'department_id' =>15]);
        City::create(['name' => 'Sotaquirá', 'department_id' =>15]);
        City::create(['name' => 'Sotara [Paispamba]', 'department_id' =>19]);
        City::create(['name' => 'Sotomayor [Los Andes]', 'department_id' =>52]);
        City::create(['name' => 'Suaita', 'department_id' =>68]);
        City::create(['name' => 'Suan', 'department_id' =>8]);
        City::create(['name' => 'Suaza', 'department_id' =>41]);
        City::create(['name' => 'Subachoque', 'department_id' =>25]);
        City::create(['name' => 'Sucre', 'department_id' =>19]);
        City::create(['name' => 'Sucre', 'department_id' =>68]);
        City::create(['name' => 'Sucre', 'department_id' =>70]);
        City::create(['name' => 'Suesca', 'department_id' =>25]);
        City::create(['name' => 'Supatá', 'department_id' =>25]);
        City::create(['name' => 'Supía', 'department_id' =>17]);
        City::create(['name' => 'Suratá', 'department_id' =>68]);
        City::create(['name' => 'Susa', 'department_id' =>25]);
        City::create(['name' => 'Susacón', 'department_id' =>15]);
        City::create(['name' => 'Sutamarchán', 'department_id' =>15]);
        City::create(['name' => 'Sutatausa', 'department_id' =>25]);
        City::create(['name' => 'Sutatenza', 'department_id' =>15]);
        City::create(['name' => 'Suárez', 'department_id' =>19]);
        City::create(['name' => 'Suárez', 'department_id' =>73]);
        City::create(['name' => 'Sácama', 'department_id' =>85]);
        City::create(['name' => 'Sáchica', 'department_id' =>15]);
        City::create(['name' => 'Tabio', 'department_id' =>25]);
        City::create(['name' => 'Tadó', 'department_id' =>27]);
        City::create(['name' => 'Talaigua Nuevo', 'department_id' =>13]);
        City::create(['name' => 'Tamalameque', 'department_id' =>20]);
        City::create(['name' => 'Tame', 'department_id' =>81]);
        City::create(['name' => 'Taminango', 'department_id' =>52]);
        City::create(['name' => 'Tangua', 'department_id' =>52]);
        City::create(['name' => 'Taraira', 'department_id' =>97]);
        City::create(['name' => 'Tarazá', 'department_id' =>5]);
        City::create(['name' => 'Tarqui', 'department_id' =>41]);
        City::create(['name' => 'Tarso', 'department_id' =>5]);
        City::create(['name' => 'Tasco', 'department_id' =>15]);
        City::create(['name' => 'Tauramena', 'department_id' =>85]);
        City::create(['name' => 'Tausa', 'department_id' =>25]);
        City::create(['name' => 'Tello', 'department_id' =>41]);
        City::create(['name' => 'Tena', 'department_id' =>25]);
        City::create(['name' => 'Tenerife', 'department_id' =>47]);
        City::create(['name' => 'Tenjo', 'department_id' =>25]);
        City::create(['name' => 'Tenza', 'department_id' =>15]);
        City::create(['name' => 'Teorama', 'department_id' =>54]);
        City::create(['name' => 'Teruel', 'department_id' =>41]);
        City::create(['name' => 'Tesalia', 'department_id' =>41]);
        City::create(['name' => 'Tibacuy', 'department_id' =>25]);
        City::create(['name' => 'Tibaná', 'department_id' =>15]);
        City::create(['name' => 'Tibasosa', 'department_id' =>15]);
        City::create(['name' => 'Tibirita', 'department_id' =>25]);
        City::create(['name' => 'Tibú', 'department_id' =>54]);
        City::create(['name' => 'Tierralta', 'department_id' =>23]);
        City::create(['name' => 'Timaná', 'department_id' =>41]);
        City::create(['name' => 'Timbiquí', 'department_id' =>19]);
        City::create(['name' => 'Timbío', 'department_id' =>19]);
        City::create(['name' => 'Tinjacá', 'department_id' =>15]);
        City::create(['name' => 'Tipacoque', 'department_id' =>15]);
        City::create(['name' => 'Tiquisio [Puerto Rico]', 'department_id' =>13]);
        City::create(['name' => 'Titiribí', 'department_id' =>5]);
        City::create(['name' => 'Toca', 'department_id' =>15]);
        City::create(['name' => 'Tocaima', 'department_id' =>25]);
        City::create(['name' => 'Tocancipá', 'department_id' =>25]);
        City::create(['name' => 'Toguí', 'department_id' =>15]);
        City::create(['name' => 'Toledo', 'department_id' =>5]);
        City::create(['name' => 'Toledo', 'department_id' =>54]);
        City::create(['name' => 'Tolú', 'department_id' =>70]);
        City::create(['name' => 'Tolú Viejo', 'department_id' =>70]);
        City::create(['name' => 'Tona', 'department_id' =>68]);
        City::create(['name' => 'Topagá', 'department_id' =>15]);
        City::create(['name' => 'Topaipí', 'department_id' =>25]);
        City::create(['name' => 'Toribío', 'department_id' =>19]);
        City::create(['name' => 'Toro', 'department_id' =>76]);
        City::create(['name' => 'Tota', 'department_id' =>15]);
        City::create(['name' => 'Totoró', 'department_id' =>19]);
        City::create(['name' => 'Trinidad', 'department_id' =>85]);
        City::create(['name' => 'Trujillo', 'department_id' =>76]);
        City::create(['name' => 'Tubará', 'department_id' =>8]);
        City::create(['name' => 'Tuchín', 'department_id' =>23]);
        City::create(['name' => 'Tulúa', 'department_id' =>76]);
        City::create(['name' => 'Tumaco', 'department_id' =>52]);
        City::create(['name' => 'Tunja', 'department_id' =>15]);
        City::create(['name' => 'Tunungua', 'department_id' =>15]);
        City::create(['name' => 'Turbaco', 'department_id' =>13]);
        City::create(['name' => 'Turbaná', 'department_id' =>13]);
        City::create(['name' => 'Turbo', 'department_id' =>5]);
        City::create(['name' => 'Turmequé', 'department_id' =>15]);
        City::create(['name' => 'Tuta', 'department_id' =>15]);
        City::create(['name' => 'Tutasá', 'department_id' =>15]);
        City::create(['name' => 'Támara', 'department_id' =>85]);
        City::create(['name' => 'Támesis', 'department_id' =>5]);
        City::create(['name' => 'Túquerres', 'department_id' =>52]);
        City::create(['name' => 'Ubalá', 'department_id' =>25]);
        City::create(['name' => 'Ubaque', 'department_id' =>25]);
        City::create(['name' => 'Ubaté', 'department_id' =>25]);
        City::create(['name' => 'Ulloa', 'department_id' =>76]);
        City::create(['name' => 'Une', 'department_id' =>25]);
        City::create(['name' => 'Unguía', 'department_id' =>27]);
        City::create(['name' => 'Unión Panamericana [ÁNIMAS]', 'department_id' =>27]);
        City::create(['name' => 'Uramita', 'department_id' =>5]);
        City::create(['name' => 'Uribe', 'department_id' =>50]);
        City::create(['name' => 'Uribia', 'department_id' =>44]);
        City::create(['name' => 'Urrao', 'department_id' =>5]);
        City::create(['name' => 'Urumita', 'department_id' =>44]);
        City::create(['name' => 'Usiacuri', 'department_id' =>8]);
        City::create(['name' => 'Valdivia', 'department_id' =>5]);
        City::create(['name' => 'Valencia', 'department_id' =>23]);
        City::create(['name' => 'Valle de San José', 'department_id' =>68]);
        City::create(['name' => 'Valle de San Juan', 'department_id' =>73]);
        City::create(['name' => 'Valle del Guamuez', 'department_id' =>86]);
        City::create(['name' => 'Valledupar', 'department_id' =>20]);
        City::create(['name' => 'Valparaiso', 'department_id' =>5]);
        City::create(['name' => 'Valparaiso', 'department_id' =>18]);
        City::create(['name' => 'Vegachí', 'department_id' =>5]);
        City::create(['name' => 'Venadillo', 'department_id' =>73]);
        City::create(['name' => 'Venecia', 'department_id' =>5]);
        City::create(['name' => 'Venecia [Ospina Pérez]', 'department_id' =>25]);
        City::create(['name' => 'Ventaquemada', 'department_id' =>15]);
        City::create(['name' => 'Vergara', 'department_id' =>25]);
        City::create(['name' => 'Versalles', 'department_id' =>76]);
        City::create(['name' => 'Vetas', 'department_id' =>68]);
        City::create(['name' => 'Viani', 'department_id' =>25]);
        City::create(['name' => 'Vigía del Fuerte', 'department_id' =>5]);
        City::create(['name' => 'Vijes', 'department_id' =>76]);
        City::create(['name' => 'Villa Caro', 'department_id' =>54]);
        City::create(['name' => 'Villa Rica', 'department_id' =>19]);
        City::create(['name' => 'Villa de Leiva', 'department_id' =>15]);
        City::create(['name' => 'Villa del Rosario', 'department_id' =>54]);
        City::create(['name' => 'Villagarzón', 'department_id' =>86]);
        City::create(['name' => 'Villagómez', 'department_id' =>25]);
        City::create(['name' => 'Villahermosa', 'department_id' =>73]);
        City::create(['name' => 'Villamaría', 'department_id' =>17]);
        City::create(['name' => 'Villanueva', 'department_id' =>13]);
        City::create(['name' => 'Villanueva', 'department_id' =>44]);
        City::create(['name' => 'Villanueva', 'department_id' =>68]);
        City::create(['name' => 'Villanueva', 'department_id' =>85]);
        City::create(['name' => 'Villapinzón', 'department_id' =>25]);
        City::create(['name' => 'Villarrica', 'department_id' =>73]);
        City::create(['name' => 'Villavicencio', 'department_id' =>50]);
        City::create(['name' => 'Villavieja', 'department_id' =>41]);
        City::create(['name' => 'Villeta', 'department_id' =>25]);
        City::create(['name' => 'Viotá', 'department_id' =>25]);
        City::create(['name' => 'Viracachá', 'department_id' =>15]);
        City::create(['name' => 'Vista Hermosa', 'department_id' =>50]);
        City::create(['name' => 'Viterbo', 'department_id' =>17]);
        City::create(['name' => 'Vélez', 'department_id' =>68]);
        City::create(['name' => 'Yacopí', 'department_id' =>25]);
        City::create(['name' => 'Yacuanquer', 'department_id' =>52]);
        City::create(['name' => 'Yaguará', 'department_id' =>41]);
        City::create(['name' => 'Yalí', 'department_id' =>5]);
        City::create(['name' => 'Yarumal', 'department_id' =>5]);
        City::create(['name' => 'Yolombó', 'department_id' =>5]);
        City::create(['name' => 'Yondó [Casabe]', 'department_id' =>5]);
        City::create(['name' => 'Yopal', 'department_id' =>85]);
        City::create(['name' => 'Yotoco', 'department_id' =>76]);
        City::create(['name' => 'Yumbo', 'department_id' =>76]);
        City::create(['name' => 'Zambrano', 'department_id' =>13]);
        City::create(['name' => 'Zapatoca', 'department_id' =>68]);
        City::create(['name' => 'Zapayán [PUNTA DE PIEDRAS]', 'department_id' =>47]);
        City::create(['name' => 'Zaragoza', 'department_id' =>5]);
        City::create(['name' => 'Zarzal', 'department_id' =>76]);
        City::create(['name' => 'Zetaquirá', 'department_id' =>15]);
        City::create(['name' => 'Zipacón', 'department_id' =>25]);
        City::create(['name' => 'Zipaquirá', 'department_id' =>25]);
        City::create(['name' => 'Zona Bananera [PRADO - SEVILLA]', 'department_id' =>47]);
        City::create(['name' => 'Ábrego', 'department_id' =>54]);
        City::create(['name' => 'Íquira', 'department_id' =>41]);
        City::create(['name' => 'Úmbita', 'department_id' =>15]);
        City::create(['name' => 'Útica', 'department_id' =>25]);

    }
}
